version: '3.8'

services:
  task-service:
    build:
      context: ./task-service
    container_name: task-tracker-task-service
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@task-tracker-db.c7e2oqegkpj1.ap-south-1.rds.amazonaws.com:5432/taskdb
    restart: unless-stopped

  analytics-service:
    build:
      context: ./analytics-service
    container_name: task-tracker-analytics-service
    ports:
      - "3001:3001"
    environment:
      - TASK_SERVICE_URL=http://task-service:3000
    depends_on:
      - task-service
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: task-tracker-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_TASK_API_URL=http://43.204.215.248:3000/task
      - VITE_ANALYTICS_API_URL=http://43.204.215.248:3001/analytics
    restart: unless-stopped